pages:
  stage: deploy
  image: hackartscience/jekyll-build:2.3
  variables:
    GIT_SSL_NO_VERIFY: 1
  before_script:
    - bundle install
  script:
    - JEKYLL_ENV=production jekyll build -d public/
    - exiftool -all= --icc_profile:all public/static/
    - mkdir compressed.public
    - cp -r public/* compressed.public/
    - gzip -r compressed.public
    - cp -r compressed.public/* public/
  artifacts:
    expire_in: 1 days
    paths:
      - public
  only:
    - master
