pages:
  stage: deploy
  image: ruby:2.3
  before_script:
    - apt-get update && apt-get install -y nodejs
    - bundle install
  script:
    - jekyll build -d public/
  artifacts:
    expire_in: 12 mos
    paths:
      - public
  only:
    - master
