# Site settings; reloaded only at server startup
encoding: utf-8
title: Juliann Ma
tagline: Pianist ℘ Interdisciplinary Artist
description: >
  A professional site for Juliann Ma, New York City based pianist, interdisciplinary artist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://juliannma.com" # the base hostname & protocol for your site

birthday: 614221261 # In standard epoch time, computes age automagically

email: art@juliannma.com

# Things that will show up in the bar of navigation links
nav_sections:
  - Biography
  - Work
  - Concerts
  - Photography
  - Press
  - Contact

# Ignore these when publishing the website
exclude:
 - media
 - Gemfile
 - Gemfile.lock
 - LICENSE
 - README.md
 - force-rebuild.sh

# Collections, needed to correctly build the website
collections:
  - events

# This is plumbing; disregard
# SSL certificate redirect is included for the "production" environment

plugins_dir: ./_plugins

# Parameters for minification
jekyll-press:
  exclude: ['*.ics', '*.txt'] # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

markdown: kramdown

kramdown:
  auto_ids:       false
