# Site settings; reloaded only at server startup
encoding: utf-8
title: Juliann Ma
tagline: Pianist ℘ Interdisciplinary Artist
description: >
  A professional site for Juliann Ma, New York City based pianist, interdisciplinary artist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://new.juliannma.com" # the base hostname & protocol for your site

birthday: 614221261 # In standard epoch time, computes age automagically

professional_email: art@juliannma.com
sponsorship_email: sponsor@juliannma.com

# Collections, needed to correctly build the website
collections:
  - events

# Build settings
markdown: kramdown
exclude:
 - Gemfile
 - Gemfile.lock
 - LICENSE
 - README.md
 - edit.sh
 - commit.sh
 - force-rebuild.sh

# Enables/disables SSL certificate redirect
production: true

plugins_dir:
  - jekyll-press

# Parameters for minification
jekyll-press:
  exclude: ['*.ics', '*.txt'] # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

kramdown:
  auto_ids:       false
